# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PythonCodeEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from line_number_code_editor import CodeEditor

class Ui_PythonCodeEditor(object):
    def setupUi(self, PythonCodeEditor):
        PythonCodeEditor.setObjectName("PythonCodeEditor")
        PythonCodeEditor.setFixedSize(598, 527)
        self.centralwidget = QtWidgets.QWidget(PythonCodeEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.editor = CodeEditor(self.centralwidget)
        self.editor.setGeometry(QtCore.QRect(0, 20, 601, 261))
        self.editor.setObjectName("editor")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 91, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 290, 91, 20))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 310, 601, 201))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.executeButton = QtWidgets.QPushButton(self.centralwidget)
        self.executeButton.setGeometry(QtCore.QRect(490, 279, 111, 31))
        self.executeButton.setObjectName("pushButton")
        PythonCodeEditor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PythonCodeEditor)
        self.statusbar.setObjectName("statusbar")
        PythonCodeEditor.setStatusBar(self.statusbar)

        self.retranslateUi(PythonCodeEditor)
        QtCore.QMetaObject.connectSlotsByName(PythonCodeEditor)

    def retranslateUi(self, PythonCodeEditor):
        _translate = QtCore.QCoreApplication.translate
        PythonCodeEditor.setWindowTitle(_translate("PythonCodeEditor", "PythonCodeEditor"))
        self.label.setText(_translate("PythonCodeEditor", "Code:"))
        self.label_2.setText(_translate("PythonCodeEditor", "Export:"))
        self.executeButton.setText(_translate("PythonCodeEditor", "Execute"))
