# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'output_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Output(object):
    def setupUi(self, Output):
        Output.setObjectName("Output")
        Output.resize(800, 530)
        self.centralwidget = QtWidgets.QWidget(Output)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 30, 801, 481))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.executeButton = QtWidgets.QPushButton(self.centralwidget)
        self.executeButton.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.executeButton.setObjectName("executeButton")
        self.saveCodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveCodeButton.setGeometry(QtCore.QRect(100, 0, 101, 31))
        self.saveCodeButton.setObjectName("saveCodeButton")
        Output.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Output)
        self.statusbar.setObjectName("statusbar")
        Output.setStatusBar(self.statusbar)

        self.retranslateUi(Output)
        QtCore.QMetaObject.connectSlotsByName(Output)

    def retranslateUi(self, Output):
        _translate = QtCore.QCoreApplication.translate
        Output.setWindowTitle(_translate("Output", "Output"))
        self.executeButton.setText(_translate("Output", "Execute"))
        self.saveCodeButton.setText(_translate("Output", "SaveCode"))
